# Generated by Django 2.1.7 on 2019-04-01 04:18

import Login.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='Documentos/', validators=[Login.validators.validate_file_extension])),
            ],
        ),
    ]
